// <auto-generated />
using System;
using EntityFramworkCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore.Data.Migrations
{
    [DbContext(typeof(FootballLeagueDbContext))]
    [Migration("20261006102606_Addingmoredata")]
    partial class Addingmoredata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("EntityFrameworkCore.Domain.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("EntityFrameworkCore.Domain.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            DateCreated = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "realmadrid"
                        },
                        new
                        {
                            TeamId = 2,
                            DateCreated = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "barcelona"
                        },
                        new
                        {
                            TeamId = 3,
                            DateCreated = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "manchester city"
                        },
                        new
                        {
                            TeamId = 4,
                            DateCreated = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "manchester united"
                        },
                        new
                        {
                            TeamId = 5,
                            DateCreated = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "liverpool"
                        },
                        new
                        {
                            TeamId = 6,
                            DateCreated = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "arsenal"
                        },
                        new
                        {
                            TeamId = 7,
                            DateCreated = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "chelsea"
                        },
                        new
                        {
                            TeamId = 8,
                            DateCreated = new DateTime(2026, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "tottenham"
                        },
                        new
                        {
                            TeamId = 9,
                            DateCreated = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "bayern munich"
                        },
                        new
                        {
                            TeamId = 10,
                            DateCreated = new DateTime(2026, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "borussia dortmund"
                        },
                        new
                        {
                            TeamId = 11,
                            DateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "inter milan"
                        },
                        new
                        {
                            TeamId = 12,
                            DateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ac milan"
                        },
                        new
                        {
                            TeamId = 13,
                            DateCreated = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "juventus"
                        },
                        new
                        {
                            TeamId = 14,
                            DateCreated = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "napoli"
                        },
                        new
                        {
                            TeamId = 15,
                            DateCreated = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "psg"
                        },
                        new
                        {
                            TeamId = 16,
                            DateCreated = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "marseille"
                        },
                        new
                        {
                            TeamId = 17,
                            DateCreated = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "realmadrid"
                        },
                        new
                        {
                            TeamId = 18,
                            DateCreated = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "barcelona"
                        },
                        new
                        {
                            TeamId = 19,
                            DateCreated = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "liverpool"
                        },
                        new
                        {
                            TeamId = 20,
                            DateCreated = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "arsenal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
