### Get all users
GET http://localhost:5281/users
Accept: application/json

### Get user by ID
GET http://localhost:5281/users/1
Accept: application/json

### Create a new user
POST http://localhost:5281/users
Content-Type: application/json

{
  "name": "Ethan Brown",
  "email": "ethan.brown@techhive.com",
  "department": "HR"
}

### Update an existing user
PUT http://localhost:5281/users/2
Content-Type: application/json

{
  "id": 2,
  "name": "Bob Smith Updated",
  "email": "bob.smith.updated@techhive.com",
  "department": "IT"
}

### Delete a user
DELETE http://localhost:5281/users/3
Accept: application/json
